services:
  web:
    build:
      context: ./../..
      dockerfile: apps/fastapi/Dockerfile
    env_file:
      - ../../packages/database/.env
    command: uvicorn app.main:api_router --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app/apps/fastapi
    ports:
      - 8000:8000
    restart: always
